### ISSUE TITLE
Replica set configurations

### ISSUE THREAD

**Issue by joaomirandasa** [valiton/grafana-mongodb-atlas-datasource#18]
First of all, amazing job made here!

I have an questions - is it possible to add an "*" on mongo selection ? because when it's running into replica-set sometimes we don't know wich mongo it's being used - i face a lot of possibilities (all my replicas) - but i want all values.. (median or something like that) 

![Captura de Tela 2020-05-09 às 11 13 30](https://user-images.githubusercontent.com/29043431/81476065-22c40a00-91e6-11ea-98ba-e87274e8c872.png)
This image represents what i talking about. 

thank you.

**Comment by adam-olema** [comment]
I am having similar issues.  It can be tedious to type out every shard, especially when they scale up/down.

**Comment by joaomirandasa** [comment]
@adam-olema Yeah! This library is really usefull! But can be more than good for us! This improvements will help to track production enviroments, we can see this repo grow with time - it's good for chasing errors and troubles on shard enviromets.

**Comment by CapChrisCap** [comment]
Hey @adam-olema , 
thank you for your feature suggestion. We are also using it as @joaomirandasa suggested. In the current implementation, there is no other way to solve this. But we would be happy about a pull request :-)
