### ISSUE TITLE
Template variables issues

### ISSUE THREAD

**Issue by bionicvapourboy** [valiton/grafana-mongodb-atlas-datasource#19]
**Description**
It is not possible to use template variables for project or shard selection.

**To Reproduce**
1. Create a template variable containing etither project name or project id and name it _projectName_
2. Insert the variable in search filter of the project dropdown
3. Unfocus the field to trigger the query
4. Get the metric error

**Expected behavior**
User should be able to select key-values option via template variables by name or value

**Additional context**
Monitoring a cluster requires a lot of duplicate panels. It could be managed easier with some tamplating variables (Eg: project name and cluster namespace)

**Comment by CapChrisCap** [comment]
Hey @bionicvapourboy 
Thank you for your feature proposal. As we said in the the README, the templating is currently not possible with our plugin. But we would be happy about a pull request :-) 
Until then, I will close this issue because we won't have time to implement this soon :-/
