### ISSUE TITLE
Error with Alerts

### ISSUE THREAD

**Issue by Kitsunees** [valiton/grafana-mongodb-atlas-datasource#2]
Hey, I was testing your plugin and it works pretty good except when I try to create an alert.

When I create an Alert and test the rule an error appears:
`error:"tsdb.HandleRequest() error rpc error: code = Internal desc = grpc: error while marshaling: proto: repeated field Results has nil element"`

I'm newbie at this so I don't really know if it's a known issue or if I did something wrong and it's my bad.

I'm using: Grafana 6.2.5 / Debian

Thanks in advance ~

**Comment by moizmmz** [comment]
Hi, 

I'm trying to install your plugin. I run Grafana on a docker container in an AWS instance and so I logged into the instance and ran:
grafana-cli --pluginUrl https://github.com/valiton/grafana-mongodb-atlas-datasource/releases/latest/download/grafana-mongodb-atlas-datasource.zip plugins install grafana-mongodb-atlas-datasource

This worked, giving me the message: ✔ Installed grafana-mongodb-atlas-datasource successfully

After this I restarted the docker container using docker restart <container_id>.

I still don't see this datasource in my grafana. 

Also, the rest of the steps like npm install, dep ensure and make just don't work on my instance. I'm new to this. pls help me

**Comment by moizmmz** [comment]
> Hey, I was testing your plugin and it works pretty good except when I try to create an alert.
> 
> When I create an Alert and test the rule an error appears:
> `error:"tsdb.HandleRequest() error rpc error: code = Internal desc = grpc: error while marshaling: proto: repeated field Results has nil element"`
> 
> I'm newbie at this so I don't really know if it's a known issue or if I did something wrong and it's my bad.
> 
> I'm using: Grafana 6.2.5 / Debian
> 
> Thanks in advance ~

**Comment by eduardomarcial** [comment]
the same with me, someone with solution ??
