### ISSUE TITLE
Grafana doesn't let unsigned plugins to be installed on version 7

### ISSUE THREAD

**Issue by Amir-Eskandari** [valiton/grafana-mongodb-atlas-datasource#20]
**Describe the bug**
I tried to install the plugin on Grafana v 7.0 using the command mentioned in the  installation part of the README.md but it doesn't install the Plugin

**To Reproduce**
1 - use the "For docker setup add the following environment variable to automatically install the plugin" part and try to install both latest version of Grafana and Plugin

**Expected behavior**
Based on read me I expected that I should have plugin installed on Grafana at the end but it just installs the Grafana itself and not the Plugin

**Screenshots**
![image](https://user-images.githubusercontent.com/30200960/84762754-81418c80-afcb-11ea-81f0-c1c346df7d26.png)

**Desktop:**
 - OS: Windows 10
 - Docker Desktop: v 2.3.0.3

**Additional context**
If I try to install Grafana v 6.5.1 it works normally as expected and it installs the plugin

**Question**
Do you have any plan in order to sign your Plugin or not ?

**Comment by CapChrisCap** [comment]
We plan to sign it (especially now after the issues with the new major release) but for now we recommend the way suggested in https://github.com/grafana/grafana/issues/24027#issuecomment-632220403: 

```
docker run \
-p 3000:3000 \
-v "$(pwd)"/grafana-plugins:/var/lib/grafana/plugins \
--name=grafana \
-e GF_INSTALL_PLUGINS="https://github.com/valiton/grafana-mongodb-atlas-datasource/releases/latest/download/grafana-mongodb-atlas-datasource.zip;grafana-mongodb-atlas-plugin" \
-e "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-mongodb-atlas-datasource" \
grafana/grafana
```

**Comment by thapakazi** [comment]
Lets document this somewhere
