### ISSUE TITLE
latest version of the grafana plugin is not working

### ISSUE THREAD

**Issue by matthiasheimerl** [valiton/grafana-mongodb-atlas-datasource#21]
**Describe the bug**
I tried to install the latest version of the plugin on my local environment for testing,  But it's not possible to do any configuration. See attached screenshot that I can't select values. When I access this page I get the error message from the second screenshot. 

**To Reproduce**
I started the docker with the following statement:

> docker run -p 3000:3000 -e GF_INSTALL_PLUGINS="https://github.com/valiton/grafana-mongodb-atlas-datasource/releases/latest/download/grafana-mongodb-atlas-datasource.zip;mongodb-atlas-datasource" grafana/grafana:6.3.2

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/68059852/87032491-0001a200-c1e5-11ea-9871-5da2b82ad047.png)

![image](https://user-images.githubusercontent.com/68059852/87032292-ad27ea80-c1e4-11ea-81f7-02729e6fe03f.png)

**Desktop (please complete the following information):**
 - OS: KDE Neon 5.19
 - Browser chrome and firefox with the latest version
- Docker version 19.03.12,

**Additional context**
When I try to install the plugin with version 1.1.0 it works as expected
https://github.com/valiton/grafana-mongodb-atlas-datasource/releases/download/v1.1.0/grafana-mongodb-atlas-datasource.zip

**Comment by CapChrisCap** [comment]
You are absolutely right, thank you for pointing that out! We reverted again to v1.1.0 and moved the major updates again in the branch `major/v2.0.0` until we fixed this. Sorry for the circumstances!
