### ISSUE TITLE
Plugin uses deprecated version of grafana's backend system

### ISSUE THREAD

**Issue by kimattree** [valiton/grafana-mongodb-atlas-datasource#26]
**Describe the bug**
grafana/grafana:latest issues a warning of plugin deprecation on startup

**To Reproduce**
1. Install plugin in grafana/grafana with env. variables:

            - 
              name: GF_INSTALL_PLUGINS
              value: https://github.com/valiton/grafana-mongodb-atlas-datasource/releases/latest/download/grafana-mongodb-atlas-datasource.zip;grafana-mongodb-atlas-plugin
            -
              name: GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS
              value: "grafana-mongodb-atlas-datasource"

2. Run as usual

**Expected behavior**
No errors or warnings

**Screenshots**
t=2020-11-06T10:30:39+0000 lvl=warn msg="Plugin uses a deprecated version of Grafana's backend plugin system which will be removed in a future release. Consider upgrading to a newer plugin version or
 reach out to the plugin repository/developer and request an upgrade." logger=plugins.backend pluginId=grafana-mongodb-atlas-datasource

**Additional context**
Precursor warning to impending breakage of plugin in future upgrades of grafana

**Comment by CapChrisCap** [comment]
Hello @kimattree, 
thanks for your issue request. We did not yet upgrade due to time and because the new [Plugin SDK](https://github.com/grafana/grafana-plugin-sdk-go) is still on development. Could you maybe support us with a Merge Request? We would really appreciate this :-)

**Comment by CapChrisCap** [comment]
Closed due to inactivity. Please re-open if required.
