### ISSUE TITLE
User/Personal API tokens are deprecated and can't be created anymore

### ISSUE THREAD

**Issue by vgarcia-te** [valiton/grafana-mongodb-atlas-datasource#27]
**Describe the bug**
The credentials based on user/personal API tokens is a deprecated feature as you can see here: https://docs.atlas.mongodb.com/configure-api-access/#personal-api-keys-deprecated
For new Atlas accounts, the creation of tokens is not enabled anymore.

Meaning that this Grafana plugin can't be used.

**To Reproduce**
N/A

**Expected behavior**
Authentication to Atlas is done using programmatic API keys https://docs.atlas.mongodb.com/configure-api-access/#atlas-prog-api-key

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A
**Additional context**
N/A

**Comment by CapChrisCap** [comment]
Thanks @vgarcia-te for the remark. We are currently updating the README, as you can see in https://github.com/valiton/grafana-mongodb-atlas-datasource/tree/major/v2.0.0#create-datasource. The current stable release already provides the new naming with public/private key.

**Comment by CapChrisCap** [comment]
Closed due to inactivity
