### ISSUE TITLE
Plugin fails to load on latest Grafana: 

### ISSUE THREAD

**Issue by fdearle** [valiton/grafana-mongodb-atlas-datasource#28]
**Describe the bug**
We updated to the latest Grafana release. Mongo DB dashboards now fail to load. The Datasource Panel for Mongo DB fails to load the plugin.

The error in the logs on startup is

```
t=2020-11-15T12:27:08+0000 lvl=warn msg="Some plugins failed to load" logger=plugins errors="[plugin \"grafana-mongodb-atlas-datasource\" is unsigned]"
```

**Comment by CapChrisCap** [comment]
Hello @fdearle, 
this is a known issue mentioned already in a few other issues. You can find the solution for this in https://github.com/valiton/grafana-mongodb-atlas-datasource/issues/20#issuecomment-644686059 or in our Readme.
