### ISSUE TITLE
problems with npm install, dep ensure and make commands

### ISSUE THREAD

**Issue by moizmmz** [valiton/grafana-mongodb-atlas-datasource#3]
Hi,

I'm trying to install your plugin. I run Grafana on a docker container in an AWS instance and so I logged into the instance and ran:
grafana-cli --pluginUrl https://github.com/valiton/grafana-mongodb-atlas-datasource/releases/latest/download/grafana-mongodb-atlas-datasource.zip plugins install grafana-mongodb-atlas-datasource

This worked, giving me the message: ✔ Installed grafana-mongodb-atlas-datasource successfully

After this I restarted the docker container using docker restart <container_id>.

I still don't see this datasource in my grafana.

Also, the rest of the steps like npm install, dep ensure and make - I try to run them on my instance. But they just don't work. I'm new to this. Pls help me.

I've tried installing nvm and then npm. Even if that works, dep is impossible.

If you have them, can you pls send me the commands you've used.

**Comment by moizmmz** [comment]
Why was this closed without being addressed?

**Comment by hereandnow** [comment]
because this is not an issue with the package. please read the readme carefully and than you will find a section on how to use the package with docker:

````
For docker setup add the following environment variable to automatically install the plugin:

docker run -p 3000:3000 -e GF_INSTALL_PLUGINS="https://github.com/valiton/grafana-mongodb-atlas-datasource/releases/latest/download/grafana-mongodb-atlas-datasource.zip;grafana-mongodb-atlas-plugin" grafana/grafana

For more information about the plugin installation have a look at the plugin official documentation.

````

npm install and so on is not necessary if you just want to use the plugin, this is for development of the plugin
