### ISSUE TITLE
Grafana Plugin

### ISSUE THREAD

**Issue by italux** [valiton/grafana-mongodb-atlas-datasource#30]
**Describe the ~bug~ question**
Do you have plans to provide this as a community plugin on [Grafana's datasource plugins page](https://grafana.com/grafana/plugins?search=atlas&type=datasource)?

**To Reproduce**
1. Go to https://grafana.com/grafana/plugins?search=atlas&type=datasource
2. Click on `Name / Description`
3. Type `MongoDB Atlas`

**Additional context**
This would be nice to allow people to share dashboard using [Import / Export feature](https://grafana.com/docs/grafana/latest/dashboards/export-import/#import-and-sharing-with-grafana-2x-or-30)

**Comment by CapChrisCap** [comment]
Hello @italux, 
sorry for the late reply. It is definitely on the road map but at first we want to upgrade the backend using the latest [Grafana SDK](https://github.com/grafana/grafana-plugin-sdk-go). However, this is currently in WIP. But we hope that we can upgrade soon and that we can also take then the next step by making this plugin official. 

I hope this answered the question. Please re-open the issue if there is anything left unclear :)
