### ISSUE TITLE
After installing, it keeps giving {"message":"Metric request error"} when trying to query

### ISSUE THREAD

**Issue by wickstargazer** [valiton/grafana-mongodb-atlas-datasource#31]
**Describe the bug**

After installing and configuration, the plugin keeps giving `{"message":"Metric request error"}` while trying to query from data source. Although the test when setting up says its successfull.

**To Reproduce**
1. Install plugin
2. try query anything
3. check network tab

**Expected behavior**

should be able to get the metrics from mongodb atlas

**Screenshots**
![image](https://user-images.githubusercontent.com/1543442/104095034-353b9980-52c7-11eb-9cd2-5dcf9781f20f.png)

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - 10

**Additional context**

I found this weird error and debug log

```
t=2021-01-09T15:01:39+0000 lvl=dbug msg="2021-01-09T15:01:39.325Z [DEBUG] mongodb-atlas-datasource: Query: datasource=\"MongoDB Atlas Logs\" TimeRange=\"fromRaw:\"1610182898211\" toRaw:\"1610204498211\" fromEpochMs:1610182898211 toEpochMs:1610204498211 \"" logger=plugins.backend pluginId=grafana-mongodb-atlas-datasource
t=2021-01-09T15:01:39+0000 lvl=dbug msg="2021-01-09T15:01:39.325Z [DEBUG] mongodb-atlas-datasource: createRequest: queryType=query" logger=plugins.backend pluginId=grafana-mongodb-atlas-datasource
t=2021-01-09T15:01:39+0000 lvl=dbug msg="2021-01-09T15:01:39.325Z [DEBUG] mongodb-atlas-datasource: MetricQuery: queryJSON=\"{\"alias\":\"advance-mongodb-m5d.flowaccount.com:27017\",\"clusterId\":\"\",\"clusterName\":\"AdvanceDBReplicaSet\",\"database\":\"\",\"datasourceId\":8,\"dimensionId\":\"SYSTEM_CPU_STEAL\",\"dimensionName\":\"System cpu steal\",\"disk\":\"\",\"intervalMs\":20000,\"maxDataPoints\":1186,\"metricId\":\"process_measurements\",\"mongoId\":\"\",\"projectName\":\"Flowaccount.com\",\"queryType\":\"query\",\"refId\":\"A\",\"type\":\"timeserie\"}\" index=0" logger=plugins.backend pluginId=grafana-mongodb-atlas-datasource
t=2021-01-09T15:01:39+0000 lvl=dbug msg="2021-01-09T15:01:39.325Z [DEBUG] mongodb-atlas-datasource: MakeHttpRequest: URL=https://cloud.mongodb.com/api/atlas/v1.0/groups//processes//measurements" logger=plugins.backend pluginId=grafana-mongodb-atlas-datasource
t=2021-01-09T15:01:39+0000 lvl=dbug msg="2021-01-09T15:01:39.325Z [DEBUG] mongodb-atlas-datasource: MakeHttpRequest: Full URL=/api/atlas/v1.0/groups//processes//measurements?end=2021-01-09T15%3A01%3A38Z&granularity=PT1M&m=SYSTEM_CPU_STEAL&start=2021-01-09T09%3A01%3A38Z" logger=plugins.backend pluginId=grafana-mongodb-atlas-datasource
t=2021-01-09T15:01:39+0000 lvl=dbug msg="2021-01-09T15:01:39.814Z [DEBUG] mongodb-atlas-datasource: MakeHttpRequest: status code error=\"invalid status code. status: 404 Not Found\"" logger=plugins.backend pluginId=grafana-mongodb-atlas-datasource
t=2021-01-09T15:01:39+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = invalid status code. status: 404 Not Found" remote_addr=101.109.238.113
t=2021-01-09T15:01:39+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=101.109.238.113 time_ms=502 size=34 referer="https://grafana.flowaccount.com/d/xHREJd6Zz/system-overview?panelId=74&edit&fullscreen&orgId=1&refresh=30s"
```

it seems its querying twice, and at the second time the `base api path` is wrong.

any suggestions?

**Comment by CapChrisCap** [comment]
Hello @wickstargazer , 
can you please also provide the arguments that you selected? As I can see from your API calls, it seems like you have not selected any parameter because the Project is missing, as well as the corresponding Mongo. 

In addition, please note that values are only accepted if you are selecting them over the dropdown menu. Only writing values into the input fields won't save the state and you will end up with empty values as you have it right now.

**Comment by wickstargazer** [comment]
The drop down is empty although the test in setting says datasource is working after entering the ip

i added project read only and monitoring admin permissions but still it does not work

**Comment by CapChrisCap** [comment]
The datasource only checks whether the API is accessible in general with the credentials but does not check the corresponding permissions. If the dropdown is empty, then your access keys are probably not legit-able to access the corresponding projects, mongos or so on. Please verify that really all the permissions are set correctly and that you really set the permissions correctly for the right project. I will close this issue now because the issue seems to be on MongoDB Atlas Permissions side. Please re-open if this assumption is wrong ;)

**Comment by wickstargazer** [comment]
@CapChrisCap I made the api permission as organization owner and project owner but it still doesn't get any value populated

**Comment by CapChrisCap** [comment]
@wickstargazer can you do an API call manually like https://docs.atlas.mongodb.com/reference/api/processes-get-all on your own computer with the provided parameters?

**Comment by wickstargazer** [comment]
![image](https://user-images.githubusercontent.com/1543442/104327109-03237500-551d-11eb-8579-8fba7b5b236f.png)

**Comment by CapChrisCap** [comment]
@wickstargazer as you see, you can now access any projects (=groups) with your credentials. The MongoDB Atlas team or StackOverflow would now be best to investigate more :)

**Comment by wickstargazer** [comment]
Found out that the base uri has to be `https://cloud.mongodb.com/api/public/v1.0/` instead of atlas, anywhere i can config it?

**Comment by CapChrisCap** [comment]
@wickstargazer it is unfortunately not configurable yet (see https://github.com/valiton/grafana-mongodb-atlas-datasource/blob/e9e521a785e967c4aadf2b0bd151410ea7e35131/pkg/atlas_datasource.go#L20) but feel free to create a pull request :-)

**Comment by wickstargazer** [comment]
i changed it but its not affected do i have to rebuild it into exe or amd64 accordingly?

**Comment by CapChrisCap** [comment]
depends how you run your Grafana, if it is docker, then Grafana runs on linux and therefore amd64
