### ISSUE TITLE
Metric "LOGICAL_SIZE" missing

### ISSUE THREAD

**Issue by wywywywy** [valiton/grafana-mongodb-atlas-datasource#32]
From the Atlas API path, `https://cloud.mongodb.com/api/atlas/v1.0/groups/PROJECT-ID/processes/HOST:PORT/measurements` I can see a "LOGICAL_SIZE" metric, and it does contain data.

However, I cannot see it in the Dimensions drop down list.

Can it be added please?

Use case: Keep an eye on the usage of M0/M2/M5 clusters and upgrade before it hits the limit.

**Comment by wywywywy** [comment]
PR open #33

**Comment by wywywywy** [comment]
Thank you for merging.

I guess a proper release will be done soon, is that right?

**Comment by CapChrisCap** [comment]
Yes, we are currently testing and the release will be available hopefully within the next days 👍

**Comment by CapChrisCap** [comment]
We added a pre-release for a new major version (updated plugin name to be ready to sign the plugin). Can you please verify that the new metric really works? For our MongoDB cluster, the metric does not seem to be available: 

```
docker run -p 3000:3000 \
  -e GF_INSTALL_PLUGINS="https://github.com/valiton/grafana-mongodb-atlas-datasource/releases/download/v2.0.0/mongodb-atlas-datasource.zip" \
  -e "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=mongodb-atlas-datasource" \
  grafana/grafana
```

**Comment by wywywywy** [comment]
Yep just tested it and it works fine.  Thank you.

Maybe this is only applicable to M0/M2/M5 clusters?

**Comment by CapChrisCap** [comment]
OK perfect, the version is now also officially released. Thanks for the MR!
