### ISSUE TITLE
Use grafana variables in query builder

### ISSUE THREAD

**Issue by mcalteau** [valiton/grafana-mongodb-atlas-datasource#51]
Grafana Variables seems to not working in query builder to set fields like project, cluster, mongo, ...
Also this datasource should populate the variables.

Both could be very usefull to build dynamic dashboards.

**Comment by CapChrisCap** [comment]
Hey @mcalteau , 
thank you for raising this issue. You are right here: currently, we are not supporting variables. 

Even if it would not be too much work to implement, I can't promise that we can implement this soon. If you have time, we would be happy about a Merge Request. 

What would be required is a change in the [QueryEditor](https://github.com/valiton/grafana-mongodb-atlas-datasource/blob/master/src/QueryEditor.tsx). There, the input values need to be replaces via

```javascript
export const SimplePanel: React.FC<Props> = ({ options, data, width, height, replaceVariables }) => {
  const query = replaceVariables('Now displaying $service');

  return <div>{query}</div>;
};
```

see https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-variables/

**Comment by CapChrisCap** [comment]
closed due to inactivity
