### ISSUE TITLE
Datasource ignoring proxy settings

### ISSUE THREAD

**Issue by hole13** [valiton/grafana-mongodb-atlas-datasource#52]
**Describe the bug**
We are currently using the Plugin in it's latest version on our internal Grafana Cluster setup. As it is located in our internal network we use a Proxy to connect to cloud.mongodb.com. The proxy is set with environment variables and picked up by Grafana and used by other Grafana Datasources (like Prometheus, Azure, ...). Just with the Atlas Datasource it seems to ignore those settings

Error message:
Get "https://cloud.mongodb.com/api/atlas/v1.0/": dial tcp: lookup cloud.mongodb.com on 127.0.0.1:53: no such host

We tried a test Grafana installation that does not need a Proxy to access cloud.mongodb.com and there we do not have any issues.

**To Reproduce**
1. Add a new datasource with all settings
2. Click on 'Save & test'
3. See error

**Expected behavior**
Successful access to the datasource

**Screenshots**
![mongodb-grafana_error](https://user-images.githubusercontent.com/47301589/144616805-1d769365-dabb-4734-bb88-2389f5453730.png)

**Desktop (please complete the following information):**
- Grafana version: 8.2.4 Enterprise
- Server: RHEL 7.9
- Plugin Version: 3.0.1

**Comment by CapChrisCap** [comment]
Hey @hole13 , 
thank you for this useful issue. I didn't know about the grafana proxy feature tbh. Can you provide more insights in how this environment variable is named and how the general proxy workflow works with Grafana (e.g. docs link). I couldn't find anything useful on the fast run while googling :-/ 
Thank you! :-)

**Comment by hole13** [comment]
Hi @CapChrisCap ,
Thanks for the fast reply.
It's not a special feature, we are setting the default proxy environment in the start script before starting Grafana:

HTTPS_PROXY=http://<PROXYSERVER>:<PROXYPORT>/
HTTP_PROXY=http://<PROXYSERVER>:<PROXYPORT>/
NO_PROXY=127.0.0.1,localhost,*.<CUSTOMDOMAINS>

For the other datasources that we are using (Prometheus, Azure, ...) this is no problem and it uses the Proxy ENVs.

Hope this helps you :D. If you nee more infos let me know.

**Comment by CapChrisCap** [comment]
Hey @hole13 , 

I identified the issue, thanks for reporting this. Could you please verify if it works with our release candidate? 

```
docker run -p 3000:3000 \
  -e GF_INSTALL_PLUGINS="https://github.com/valiton/grafana-mongodb-atlas-datasource/releases/download/v3.1.0-rc1/valiton-mongodbatlas-datasource.zip;valiton-mongodbatlas-datasource" \
  -e "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=valiton-mongodbatlas-datasource" \
grafana/grafana:8.0.0
```

Thanks :)

**Comment by hole13** [comment]
Hi @CapChrisCap,

sorry for the late reply. I was now able to finally test the new version and it works fine.

Thank you for the fix :D
