### ISSUE TITLE
I got an error using the plugin

### ISSUE THREAD

**Issue by EnolMG** [valiton/grafana-mongodb-atlas-datasource#55]
Hello,

I have grafana 8.1.5 installed in my kubernetes cluster and I had installed this plugin following the steps but when I'm going to use it, I got this error:

Fetch error: 404 Instantiating https://gf.hocelot.com/public/plugins/valiton-mongodbatlas-datasource/module.js Loading plugins/valiton-mongodbatlas-datasource/module

I check the logs but I only see this:

t=2022-08-23T07:44:41+0000 lvl=info msg="Request Completed" logger=context userId=2 orgId=1 uname=user method=GET path="/public/img/icons/unicons/icon-gf icon-gf-panel.svg" status=404 remote_addr=79.116.135.61 time_ms=19 size=111469 referer=https://gf.hocelot.com/plugins/valiton-mongodbatlas-datasource/

**Comment by CapChrisCap** [comment]
Hi @EnolMG , 
sorry, I did not see the notification of this issue. Is this still an issue? 
Best, Christoph

**Comment by CapChrisCap** [comment]
closed due to inactivity, please re-open if still an issue :-)
